"use client";
import {useMemo,useState} from "react";
type ApiTrip={destination:string;country:string;transport:number;stay:number;food:number;local:number;activities:number;buffer:number;total:number;confidence:"estimate"|"mixed"|"live";sources:string[]};
type Trip={id:string;place:string;region:string;emoji:string;tag:string;vibe:string;base:number;transport:number;stay:number;spend:number};
const trips:Trip[]=[
{id:"nola",place:"New Orleans",region:"Louisiana",emoji:"⚜️",tag:"Food + culture",vibe:"Culture",base:950,transport:0,stay:438,spend:512},
{id:"cancun",place:"Cancún",region:"Mexico",emoji:"🌴",tag:"Beach escape",vibe:"Beach",base:1925,transport:520,stay:690,spend:715},
{id:"denver",place:"Denver",region:"Colorado",emoji:"🏔️",tag:"Mountains + city",vibe:"Adventure",base:1635,transport:410,stay:585,spend:640},
{id:"bigbend",place:"Big Bend",region:"Texas",emoji:"🌵",tag:"Road trip",vibe:"Outdoors",base:1185,transport:240,stay:520,spend:425},
{id:"sanjuan",place:"San Juan",region:"Puerto Rico",emoji:"🌊",tag:"Island + culture",vibe:"Beach",base:2260,transport:650,stay:760,spend:850},
{id:"nashville",place:"Nashville",region:"Tennessee",emoji:"🎸",tag:"Music weekend",vibe:"Culture",base:1440,transport:365,stay:510,spend:565}
,
{id:"destin",place:"Destin",region:"Florida",emoji:"☀️",tag:"Gulf beach",vibe:"Beach",base:1680,transport:310,stay:760,spend:610},
{id:"vegas",place:"Las Vegas",region:"Nevada",emoji:"🎲",tag:"Entertainment",vibe:"Nightlife",base:1760,transport:390,stay:590,spend:780},
{id:"mexcity",place:"Mexico City",region:"Mexico",emoji:"🌮",tag:"Food + design",vibe:"Culture",base:1710,transport:490,stay:540,spend:680},
{id:"costarica",place:"Guanacaste",region:"Costa Rica",emoji:"🦥",tag:"Beach + adventure",vibe:"Adventure",base:2475,transport:720,stay:820,spend:935},
{id:"sandiego",place:"San Diego",region:"California",emoji:"🌅",tag:"Coast + city",vibe:"Beach",base:2180,transport:520,stay:880,spend:780},
{id:"smokies",place:"Great Smoky Mountains",region:"Tennessee",emoji:"🌲",tag:"Cabin + outdoors",vibe:"Outdoors",base:1510,transport:280,stay:690,spend:540},
{id:"nyc",place:"New York City",region:"New York",emoji:"🗽",tag:"Big city",vibe:"City",base:2590,transport:560,stay:1120,spend:910},
{id:"chicago",place:"Chicago",region:"Illinois",emoji:"🏙️",tag:"Food + city",vibe:"City",base:1840,transport:420,stay:720,spend:700}
];
export default function Home(){
const [budget,setBudget]=useState(2000),[origin,setOrigin]=useState("Houston, TX"),[travelers,setTravelers]=useState(2),[days,setDays]=useState(4),[searched,setSearched]=useState(false),[vibe,setVibe]=useState("Any"),[saved,setSaved]=useState<string[]>([]),[selected,setSelected]=useState<Trip|null>(null),[apiTrips,setApiTrips]=useState<ApiTrip[]>([]),[loading,setLoading]=useState(false),[dateMode,setDateMode]=useState("Flexible"),[startDate,setStartDate]=useState(""),[tripStyle,setTripStyle]=useState<"balanced"|"stay"|"experiences">("balanced");
const results=useMemo(()=>trips.filter(t=>vibe==="Any"||t.vibe===vibe).map(t=>({...t,total:Math.round(t.base*(travelers/2)*(days/4))})).sort((a,b)=>{const af=a.total<=budget?0:1,bf=b.total<=budget?0:1;return af-bf||Math.abs(budget-a.total)-Math.abs(budget-b.total)}),[budget,travelers,days,vibe]);
const searchTrips=async()=>{setSearched(true);setLoading(true);try{const res=await fetch("/api/trips",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({origin,budget,travelers,days,vibe,startDate:startDate||undefined,dateMode})});const data=await res.json();setApiTrips(data.results||[])}finally{setLoading(false)}};
const surprise=()=>{setSearched(true);const fits=results.filter(x=>x.total<=budget);const pool=fits.length?fits:results;setSelected(pool[Math.floor(Math.random()*pool.length)])};
return <main>
<header><div className="brand">roam<b>within</b></div><nav><button className="plain">Saved {saved.length>0?"("+saved.length+")":""}</button><span className="avatar">JS</span></nav></header>
<section className="hero"><span className="eyebrow">VACATIONS THAT FIT YOUR REAL BUDGET</span><h1>Start with what you want to spend.<br/><em>We’ll find where you can go.</em></h1><p>Flights, stays, food, local transportation and things to do — planned together around one number.</p>
<div className="planner"><label><small>TOTAL BUDGET</small><div className="money">$ <input type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></div></label><label><small>LEAVING FROM</small><input value={origin} onChange={e=>setOrigin(e.target.value)}/></label><label><small>TRAVELERS</small><select value={travelers} onChange={e=>setTravelers(Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label><small>TRIP LENGTH</small><select value={days} onChange={e=>setDays(Number(e.target.value))}>{[2,3,4,5,6,7].map(n=><option key={n} value={n}>{n} days</option>)}</select></label><button className="primary" onClick={searchTrips}>Show me my trips →</button></div><div className="dates"><span>WHEN?</span><button className={dateMode==="Flexible"?"active":""} onClick={()=>setDateMode("Flexible")}>Flexible dates</button><button className={dateMode==="Exact"?"active":""} onClick={()=>setDateMode("Exact")}>Exact start</button>{dateMode==="Exact"&&<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/>}</div>
<div className="vibes">{["Any","Beach","Adventure","Outdoors","Culture","City","Nightlife"].map(v=><button key={v} className={vibe===v?"active":""} onClick={()=>{setVibe(v);setSearched(true)}}>{v}</button>)}</div><button className="surprise" onClick={surprise}>✦ Surprise me instead</button></section>
<section className="trust"><div><b>One budget.</b><span>We price the whole trip.</span></div><div><b>Domestic + international.</b><span>Compare side by side.</span></div><div><b>Transparent pricing.</b><span>Live vs. estimated stays clear.</span></div></section>
{searched?<section className="results"><div className="resultHead"><div><span className="eyebrow">BEST FITS FROM {origin.toUpperCase()}</span><h2>Here’s what <em>{"$"+budget.toLocaleString()}</em> can do.</h2></div><div><small>YOUR BUDGET</small><strong>{"$"+budget.toLocaleString()}</strong></div></div><div className="resultTools"><span>{loading?"Searching vacation possibilities…":(apiTrips.length||results.length)+" vacation ideas matched"}</span><span>{apiTrips.length?"Trip engine results · validation pricing":"Best budget fit first"}</span></div><div className="cards">
{(apiTrips.length?apiTrips.map((a,i)=>({id:a.destination.toLowerCase().replace(/[^a-z0-9]+/g,"-"),place:a.destination,region:a.country,emoji:"✦",tag:a.confidence==="live"?"Live pricing":"Budget fit",vibe:"Any",base:a.total,transport:a.transport,stay:a.stay,spend:a.food+a.local+a.activities+a.buffer,total:a.total})):results).map((t,i)=>{const left=budget-t.total;return <article className="card" key={t.id}><div className="visual"><span className="rank">#{i+1} MATCH</span><span className="emoji">{t.emoji}</span><button className={"heart "+(saved.includes(t.id)?"on":"")} onClick={()=>setSaved(s=>s.includes(t.id)?s.filter(x=>x!==t.id):s.concat(t.id))}>♥</button><span className="tag">{t.tag}</span></div><div className="body"><div className="top"><div><h3>{t.place}</h3><p>{t.region} · {days} days · {travelers} traveler{travelers===1?"":"s"}</p></div><div className="price"><b>{"$"+t.total.toLocaleString()}</b><span>estimated total</span></div></div><div className={"fit "+(left>=0?"good":"over")}>{left>=0?"$"+left.toLocaleString()+" left in your budget":"$"+Math.abs(left).toLocaleString()+" over budget"}</div><div className="breakdown"><span>Transport<b>{"$"+Math.round(t.transport*(travelers/2)).toLocaleString()}</b></span><span>Stay<b>{"$"+Math.round(t.stay*(days/4)).toLocaleString()}</b></span><span>On-trip<b>{"$"+Math.round(t.spend*(travelers/2)*(days/4)).toLocaleString()}</b></span></div><button className="view" onClick={()=>setSelected(t)}>View complete trip →</button></div></article>})}</div></section>:<section className="explain"><span className="eyebrow">NOT ANOTHER ITINERARY GENERATOR</span><h2>Shop the <em>whole vacation.</em></h2><p>Most travel sites ask where you’re going, then make you discover what it costs. We flip that around.</p><div className="flow"><div><small>YOU TELL US</small><b>$2,000</b><span>4 days · 2 people · from Houston</span></div><i>→</i><div><small>WE SHOW YOU</small><b>Trips you can afford</b><span>transport + stay + spending + experiences</span></div></div></section>}
{selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">COMPLETE TRIP</span><h2>{selected.emoji} {selected.place}</h2><p>{days} days · {travelers} traveler{travelers===1?"":"s"} · from {origin}</p><div className="total"><span>Recommended trip budget</span><b>{"$"+Math.round((selected.transport+selected.stay+selected.spend)*(tripStyle==="stay"?1.08:tripStyle==="experiences"?1.05:1)).toLocaleString()}</b></div><div className="stylePick"><span>SHAPE THIS TRIP</span><div><button className={tripStyle==="balanced"?"active":""} onClick={()=>setTripStyle("balanced")}>Balanced</button><button className={tripStyle==="stay"?"active":""} onClick={()=>setTripStyle("stay")}>Better stay</button><button className={tripStyle==="experiences"?"active":""} onClick={()=>setTripStyle("experiences")}>More experiences</button></div></div><div className="wallet"><div><span>Transportation</span><b>{"$"+selected.transport.toLocaleString()}</b></div><div><span>Stay</span><b>{"$"+Math.round(selected.stay*(tripStyle==="stay"?1.22:tripStyle==="experiences"?.92:1)).toLocaleString()}</b></div><div><span>On-trip budget</span><b>{"$"+Math.round(selected.spend*(tripStyle==="experiences"?1.18:tripStyle==="stay"?.93:1)).toLocaleString()}</b></div></div><h4>Built into this trip</h4><div className="checks">✓ Transportation plan<br/>✓ Lodging budget<br/>✓ Food allowance<br/>✓ Local transportation<br/>✓ Experiences allowance<br/>✓ Safety buffer</div><p className="note">Prototype prices are validation estimates. Production will clearly separate current bookable prices from estimated on-trip spending.</p><button className="primary wide">See booking options →</button></div></div>}
<footer><b>roamwithin</b><span>Budget-first travel discovery · validation prototype</span></footer>
</main>
}